const sumo = {
  id: 13737,
  id_str: "13737",
  name: "Noah Kagan",
  screen_name: "noahkagan",
  location: "Austin, TX",
  description:
    "I’m the 🌮 loving Chief Sumo at @appsumo. I was employee #30 at Facebook. I teach everything I know about marketing & business on my YouTube channel👇",
  url: "https://t.co/2LCjbM8NpT",
  entities: { url: [Object], description: [Object] },
  protected: false,
  followers_count: 67230,
  friends_count: 161,
  listed_count: 2867,
  created_at: "Wed Nov 22 01:38:27 +0000 2006",
  favourites_count: 11541,
  utc_offset: null,
  time_zone: null,
  geo_enabled: true,
  verified: true,
  statuses_count: 19123,
  lang: null,
  contributors_enabled: false,
  is_translator: false,
  is_translation_enabled: false,
  profile_background_color: "ECECEC",
  profile_background_image_url:
    "http://abs.twimg.com/images/themes/theme1/bg.png",
  profile_background_image_url_https:
    "https://abs.twimg.com/images/themes/theme1/bg.png",
  profile_background_tile: false,
  profile_image_url:
    "http://pbs.twimg.com/profile_images/874640458240184320/53G2ALd5_normal.jpg",
  profile_image_url_https:
    "https://pbs.twimg.com/profile_images/874640458240184320/53G2ALd5_normal.jpg",
  profile_banner_url: "https://pbs.twimg.com/profile_banners/13737/1497365654",
  profile_link_color: "2BBD3E",
  profile_sidebar_border_color: "FFFFFF",
  profile_sidebar_fill_color: "E0FF92",
  profile_text_color: "000000",
  profile_use_background_image: true,
  has_extended_profile: true,
  default_profile: false,
  default_profile_image: false,
  following: false,
  follow_request_sent: false,
  notifications: false,
  translator_type: "none",
};

const odanz = {
  id: 2489830678,
  id_str: "2489830678",
  name: "Kelvin Odanz",
  screen_name: "MrOdanz",
  location: "Karshen Duniya Tsirara",
  description:
    "An advocate for absolute freedom and the anarchy that follows. Alea iacta est\n\n |•A PARODY•|  politics, comms, agribusiness & PR.",
  url: null,
  entities: { description: [Object] },
  protected: false,
  followers_count: 57969,
  friends_count: 385,
  listed_count: 116,
  created_at: "Thu Apr 17 12:49:16 +0000 2014",
  favourites_count: 662,
  utc_offset: null,
  time_zone: null,
  geo_enabled: true,
  verified: false,
  statuses_count: 57849,
  lang: null,
  contributors_enabled: false,
  is_translator: false,
  is_translation_enabled: false,
  profile_background_color: "000000",
  profile_background_image_url:
    "http://abs.twimg.com/images/themes/theme1/bg.png",
  profile_background_image_url_https:
    "https://abs.twimg.com/images/themes/theme1/bg.png",
  profile_background_tile: false,
  profile_image_url:
    "http://pbs.twimg.com/profile_images/1212275193407791105/-dHD5bW5_normal.jpg",
  profile_image_url_https:
    "https://pbs.twimg.com/profile_images/1212275193407791105/-dHD5bW5_normal.jpg",
  profile_banner_url:
    "https://pbs.twimg.com/profile_banners/2489830678/1589882831",
  profile_link_color: "19CF86",
  profile_sidebar_border_color: "000000",
  profile_sidebar_fill_color: "000000",
  profile_text_color: "000000",
  profile_use_background_image: false,
  has_extended_profile: true,
  default_profile: false,
  default_profile_image: false,
  following: false,
  follow_request_sent: false,
  notifications: false,
  translator_type: "none",
};
